sudo: required
language: rust
rust:
  - nightly
cache: cargo
script:
  - cargo build

after_success:
  - |
    if [[ "${TRAVIS_TAG:-}" != "" && "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo build --release;
      cargo install --force cargo-deb;
      cargo deb --no-build --no-strip;
    fi

deploy:
  provider: releases
  api_key:
    secure: nBET2y+bgZlsgCrg5fRi7t1RsSgDJiM4MZrezgHDrB4fiHVqjRoAm4Y8nK9Oyo8h/PG8Ms7jyUcl4H8SQSvZ+++xnYfvyiW45dWi1lwrTJ/Q6yMKk+ul0qORyjWt8+3iU0JtMMyMCxKaznx48ylr1v2iBOCxei2PH12SUIchkttSDKvxFNckyytjgxYX04uYrCe/GbCoqjsQOigDZLlcMZm56vBbnitFiefeLBosT1FkhZY/wSo/D/uGUG0B45ZDhdk+1pHMz7rlTr/7B6hSvBkZi9tLRmJRx3uxnPS47CKAho6y35BviP53AMD7VIK4PRfykqn8rcI/FJJO+FXxaSxC95xbE5Zej9LO1ywaW/M+OTY4MVGWrwM+AuTriUmAuTQqcan8lthZ3vc7y5rwP6IUYp5r35bLilJwVS8K0lBRzIcRVftQ0uncUbLAnBOBx/pnVeh/Yp8+4w6et8NsiNvF/yteekdRkWv0J8kXe2VitnQjvgyBlgce+1zOyByEdy/RxccZd7NPp++gLaZt2P0NGiMJ9p+xkPzmT4JnUuVu5sYOzUj0KuQX79WueLbrlU/QBAJENXPbPtmUiOu+by3fY4hIzmrPv5tke5C23ppa5fvRuvfdkdWp3m9vYI7FSk6qf4+gQrl6I+LKxpotY08S5KqEC6G29OyFLEabkzc=
  file_glob: true
  file:
    - target/release/fasttext-serving
    - target/release/fasttext-serving*.deb
  skip_cleanup: true
  on:
    tags: true
